// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0--rc3
// source: encounters_service.proto

package encounters

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncounterStatus int32

const (
	EncounterStatus_ACTIVE   EncounterStatus = 0
	EncounterStatus_DRAFT    EncounterStatus = 1
	EncounterStatus_ARCHIVED EncounterStatus = 2
)

// Enum value maps for EncounterStatus.
var (
	EncounterStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "DRAFT",
		2: "ARCHIVED",
	}
	EncounterStatus_value = map[string]int32{
		"ACTIVE":   0,
		"DRAFT":    1,
		"ARCHIVED": 2,
	}
)

func (x EncounterStatus) Enum() *EncounterStatus {
	p := new(EncounterStatus)
	*p = x
	return p
}

func (x EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounters_service_proto_enumTypes[0].Descriptor()
}

func (EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounters_service_proto_enumTypes[0]
}

func (x EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterStatus.Descriptor instead.
func (EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{0}
}

type EncounterType int32

const (
	EncounterType_SOCIAL   EncounterType = 0
	EncounterType_LOCATION EncounterType = 1
	EncounterType_MISC     EncounterType = 2
)

// Enum value maps for EncounterType.
var (
	EncounterType_name = map[int32]string{
		0: "SOCIAL",
		1: "LOCATION",
		2: "MISC",
	}
	EncounterType_value = map[string]int32{
		"SOCIAL":   0,
		"LOCATION": 1,
		"MISC":     2,
	}
)

func (x EncounterType) Enum() *EncounterType {
	p := new(EncounterType)
	*p = x
	return p
}

func (x EncounterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterType) Descriptor() protoreflect.EnumDescriptor {
	return file_encounters_service_proto_enumTypes[1].Descriptor()
}

func (EncounterType) Type() protoreflect.EnumType {
	return &file_encounters_service_proto_enumTypes[1]
}

func (x EncounterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterType.Descriptor instead.
func (EncounterType) EnumDescriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{1}
}

type Encounter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                        // Jedinstveni identifikator susreta.
	Name             string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                    // Ime susreta.
	Description      string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                      // Opis susreta.
	XpPoints         int32           `protobuf:"varint,4,opt,name=xp_points,json=xpPoints,proto3" json:"xp_points,omitempty"`                           // XP poeni susreta.
	Status           EncounterStatus `protobuf:"varint,5,opt,name=status,proto3,enum=EncounterStatus" json:"status,omitempty"`                          // Status susreta.
	Type             EncounterType   `protobuf:"varint,6,opt,name=type,proto3,enum=EncounterType" json:"type,omitempty"`                                // Tip susreta.
	Latitude         float64         `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`                                          // Geografska širina.
	Longitude        float64         `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`                                        // Geografska dužina.
	ShouldBeApproved bool            `protobuf:"varint,9,opt,name=should_be_approved,json=shouldBeApproved,proto3" json:"should_be_approved,omitempty"` // Da li susret treba da bude odobren.
}

func (x *Encounter) Reset() {
	*x = Encounter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Encounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Encounter) ProtoMessage() {}

func (x *Encounter) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Encounter.ProtoReflect.Descriptor instead.
func (*Encounter) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{0}
}

func (x *Encounter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Encounter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Encounter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Encounter) GetXpPoints() int32 {
	if x != nil {
		return x.XpPoints
	}
	return 0
}

func (x *Encounter) GetStatus() EncounterStatus {
	if x != nil {
		return x.Status
	}
	return EncounterStatus_ACTIVE
}

func (x *Encounter) GetType() EncounterType {
	if x != nil {
		return x.Type
	}
	return EncounterType_SOCIAL
}

func (x *Encounter) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Encounter) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Encounter) GetShouldBeApproved() bool {
	if x != nil {
		return x.ShouldBeApproved
	}
	return false
}

type CreateEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                    // Ime susreta.
	Description      string          `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                      // Opis susreta.
	XpPoints         int32           `protobuf:"varint,3,opt,name=xp_points,json=xpPoints,proto3" json:"xp_points,omitempty"`                           // XP poeni susreta.
	Status           EncounterStatus `protobuf:"varint,4,opt,name=status,proto3,enum=EncounterStatus" json:"status,omitempty"`                          // Status susreta.
	Type             EncounterType   `protobuf:"varint,5,opt,name=type,proto3,enum=EncounterType" json:"type,omitempty"`                                // Tip susreta.
	Latitude         float64         `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`                                          // Geografska širina.
	Longitude        float64         `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`                                        // Geografska dužina.
	ShouldBeApproved bool            `protobuf:"varint,8,opt,name=should_be_approved,json=shouldBeApproved,proto3" json:"should_be_approved,omitempty"` // Da li susret treba da bude odobren.
}

func (x *CreateEncounterRequest) Reset() {
	*x = CreateEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncounterRequest) ProtoMessage() {}

func (x *CreateEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncounterRequest.ProtoReflect.Descriptor instead.
func (*CreateEncounterRequest) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEncounterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEncounterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEncounterRequest) GetXpPoints() int32 {
	if x != nil {
		return x.XpPoints
	}
	return 0
}

func (x *CreateEncounterRequest) GetStatus() EncounterStatus {
	if x != nil {
		return x.Status
	}
	return EncounterStatus_ACTIVE
}

func (x *CreateEncounterRequest) GetType() EncounterType {
	if x != nil {
		return x.Type
	}
	return EncounterType_SOCIAL
}

func (x *CreateEncounterRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateEncounterRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateEncounterRequest) GetShouldBeApproved() bool {
	if x != nil {
		return x.ShouldBeApproved
	}
	return false
}

// Poruka koja se koristi za odgovor na zahtev za kreiranje susreta.
type CreateEncounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounter *Encounter `protobuf:"bytes,1,opt,name=encounter,proto3" json:"encounter,omitempty"` // Kreirani susret.
}

func (x *CreateEncounterResponse) Reset() {
	*x = CreateEncounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEncounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncounterResponse) ProtoMessage() {}

func (x *CreateEncounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncounterResponse.ProtoReflect.Descriptor instead.
func (*CreateEncounterResponse) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEncounterResponse) GetEncounter() *Encounter {
	if x != nil {
		return x.Encounter
	}
	return nil
}

// GET ALL
type GetAllEncountersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllEncountersRequest) Reset() {
	*x = GetAllEncountersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllEncountersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEncountersRequest) ProtoMessage() {}

func (x *GetAllEncountersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEncountersRequest.ProtoReflect.Descriptor instead.
func (*GetAllEncountersRequest) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{3}
}

type GetAllEncountersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounters []*Encounter `protobuf:"bytes,1,rep,name=encounters,proto3" json:"encounters,omitempty"`
}

func (x *GetAllEncountersResponse) Reset() {
	*x = GetAllEncountersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllEncountersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEncountersResponse) ProtoMessage() {}

func (x *GetAllEncountersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEncountersResponse.ProtoReflect.Descriptor instead.
func (*GetAllEncountersResponse) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllEncountersResponse) GetEncounters() []*Encounter {
	if x != nil {
		return x.Encounters
	}
	return nil
}

// GETBYID
type GetEncounterByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Jedinstveni identifikator susreta
}

func (x *GetEncounterByIDRequest) Reset() {
	*x = GetEncounterByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEncounterByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEncounterByIDRequest) ProtoMessage() {}

func (x *GetEncounterByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEncounterByIDRequest.ProtoReflect.Descriptor instead.
func (*GetEncounterByIDRequest) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetEncounterByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEncounterByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounter *Encounter `protobuf:"bytes,1,opt,name=encounter,proto3" json:"encounter,omitempty"` // Susret koji je pronađen
}

func (x *GetEncounterByIDResponse) Reset() {
	*x = GetEncounterByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEncounterByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEncounterByIDResponse) ProtoMessage() {}

func (x *GetEncounterByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEncounterByIDResponse.ProtoReflect.Descriptor instead.
func (*GetEncounterByIDResponse) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetEncounterByIDResponse) GetEncounter() *Encounter {
	if x != nil {
		return x.Encounter
	}
	return nil
}

type EncounterExecution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                               // Jedinstveni identifikator izvršenja susreta.
	UserId         int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // ID korisnika.
	EncounterId    string `protobuf:"bytes,3,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`          // ID susreta.
	CompletionTime string `protobuf:"bytes,4,opt,name=completion_time,json=completionTime,proto3" json:"completion_time,omitempty"` // Vreme završetka izvršenja.
	IsCompleted    bool   `protobuf:"varint,5,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`         // Da li je izvršenje završeno.
}

func (x *EncounterExecution) Reset() {
	*x = EncounterExecution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncounterExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterExecution) ProtoMessage() {}

func (x *EncounterExecution) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterExecution.ProtoReflect.Descriptor instead.
func (*EncounterExecution) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{7}
}

func (x *EncounterExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EncounterExecution) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EncounterExecution) GetEncounterId() string {
	if x != nil {
		return x.EncounterId
	}
	return ""
}

func (x *EncounterExecution) GetCompletionTime() string {
	if x != nil {
		return x.CompletionTime
	}
	return ""
}

func (x *EncounterExecution) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

type CreateExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // ID korisnika.
	EncounterId    string `protobuf:"bytes,2,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`          // ID susreta.
	CompletionTime string `protobuf:"bytes,3,opt,name=completion_time,json=completionTime,proto3" json:"completion_time,omitempty"` // Vreme završetka susreta (u formatu koji vam odgovara).
	IsCompleted    bool   `protobuf:"varint,4,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`         // Da li je susret završen.W
}

func (x *CreateExecutionRequest) Reset() {
	*x = CreateExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutionRequest) ProtoMessage() {}

func (x *CreateExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutionRequest.ProtoReflect.Descriptor instead.
func (*CreateExecutionRequest) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateExecutionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateExecutionRequest) GetEncounterId() string {
	if x != nil {
		return x.EncounterId
	}
	return ""
}

func (x *CreateExecutionRequest) GetCompletionTime() string {
	if x != nil {
		return x.CompletionTime
	}
	return ""
}

func (x *CreateExecutionRequest) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

type CreateExecutionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Execution *EncounterExecution `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"` // Kreirani susret.
}

func (x *CreateExecutionResponse) Reset() {
	*x = CreateExecutionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutionResponse) ProtoMessage() {}

func (x *CreateExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutionResponse.ProtoReflect.Descriptor instead.
func (*CreateExecutionResponse) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateExecutionResponse) GetExecution() *EncounterExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

// GETALL
type GetAllExecutionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllExecutionsRequest) Reset() {
	*x = GetAllExecutionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExecutionsRequest) ProtoMessage() {}

func (x *GetAllExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExecutionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{10}
}

type GetAllExecutionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Executions []*EncounterExecution `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
}

func (x *GetAllExecutionsResponse) Reset() {
	*x = GetAllExecutionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExecutionsResponse) ProtoMessage() {}

func (x *GetAllExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExecutionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllExecutionsResponse) GetExecutions() []*EncounterExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

type GetExecutionByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetExecutionByUserIdRequest) Reset() {
	*x = GetExecutionByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExecutionByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionByUserIdRequest) ProtoMessage() {}

func (x *GetExecutionByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetExecutionByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetExecutionByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Execution *EncounterExecution `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
}

func (x *GetExecutionByUserIdResponse) Reset() {
	*x = GetExecutionByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExecutionByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionByUserIdResponse) ProtoMessage() {}

func (x *GetExecutionByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetExecutionByUserIdResponse) GetExecution() *EncounterExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type UpdateExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UpdateExecutionRequest) Reset() {
	*x = UpdateExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutionRequest) ProtoMessage() {}

func (x *UpdateExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutionRequest.ProtoReflect.Descriptor instead.
func (*UpdateExecutionRequest) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateExecutionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateExecutionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateExecutionResponse) Reset() {
	*x = UpdateExecutionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutionResponse) ProtoMessage() {}

func (x *UpdateExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutionResponse.ProtoReflect.Descriptor instead.
func (*UpdateExecutionResponse) Descriptor() ([]byte, []int) {
	return file_encounters_service_proto_rawDescGZIP(), []int{15}
}

var File_encounters_service_proto protoreflect.FileDescriptor

var file_encounters_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x02, 0x0a, 0x09, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x78, 0x70, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x78, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x5f, 0x62, 0x65,
	0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x10, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x42, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x64, 0x22, 0xa1, 0x02, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x78, 0x70, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x78, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x28, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x68, 0x6f, 0x75, 0x6c,
	0x64, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x10, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x42, 0x65, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x43, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22, 0x29, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0xac,
	0x01, 0x0a, 0x12, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73,
	0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0xa0, 0x01,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x22, 0x4c, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x19,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x35, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x51, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x31, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2a, 0x36, 0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41,
	0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x33, 0x0a, 0x0d, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x4f,
	0x43, 0x49, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x49, 0x53, 0x43, 0x10, 0x02, 0x32, 0xf3,
	0x01, 0x0a, 0x10, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x70, 0x63, 0x12, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x52, 0x70, 0x63, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x70, 0x63, 0x12,
	0x18, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd1, 0x02, 0x0a, 0x19, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x47, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x70, 0x63, 0x12, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x70, 0x63, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52,
	0x70, 0x63, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x70, 0x63, 0x12, 0x17, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encounters_service_proto_rawDescOnce sync.Once
	file_encounters_service_proto_rawDescData = file_encounters_service_proto_rawDesc
)

func file_encounters_service_proto_rawDescGZIP() []byte {
	file_encounters_service_proto_rawDescOnce.Do(func() {
		file_encounters_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_encounters_service_proto_rawDescData)
	})
	return file_encounters_service_proto_rawDescData
}

var file_encounters_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_encounters_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_encounters_service_proto_goTypes = []interface{}{
	(EncounterStatus)(0),                 // 0: EncounterStatus
	(EncounterType)(0),                   // 1: EncounterType
	(*Encounter)(nil),                    // 2: Encounter
	(*CreateEncounterRequest)(nil),       // 3: CreateEncounterRequest
	(*CreateEncounterResponse)(nil),      // 4: CreateEncounterResponse
	(*GetAllEncountersRequest)(nil),      // 5: GetAllEncountersRequest
	(*GetAllEncountersResponse)(nil),     // 6: GetAllEncountersResponse
	(*GetEncounterByIDRequest)(nil),      // 7: GetEncounterByIDRequest
	(*GetEncounterByIDResponse)(nil),     // 8: GetEncounterByIDResponse
	(*EncounterExecution)(nil),           // 9: EncounterExecution
	(*CreateExecutionRequest)(nil),       // 10: CreateExecutionRequest
	(*CreateExecutionResponse)(nil),      // 11: CreateExecutionResponse
	(*GetAllExecutionsRequest)(nil),      // 12: GetAllExecutionsRequest
	(*GetAllExecutionsResponse)(nil),     // 13: GetAllExecutionsResponse
	(*GetExecutionByUserIdRequest)(nil),  // 14: GetExecutionByUserIdRequest
	(*GetExecutionByUserIdResponse)(nil), // 15: GetExecutionByUserIdResponse
	(*UpdateExecutionRequest)(nil),       // 16: UpdateExecutionRequest
	(*UpdateExecutionResponse)(nil),      // 17: UpdateExecutionResponse
}
var file_encounters_service_proto_depIdxs = []int32{
	0,  // 0: Encounter.status:type_name -> EncounterStatus
	1,  // 1: Encounter.type:type_name -> EncounterType
	0,  // 2: CreateEncounterRequest.status:type_name -> EncounterStatus
	1,  // 3: CreateEncounterRequest.type:type_name -> EncounterType
	2,  // 4: CreateEncounterResponse.encounter:type_name -> Encounter
	2,  // 5: GetAllEncountersResponse.encounters:type_name -> Encounter
	2,  // 6: GetEncounterByIDResponse.encounter:type_name -> Encounter
	9,  // 7: CreateExecutionResponse.execution:type_name -> EncounterExecution
	9,  // 8: GetAllExecutionsResponse.executions:type_name -> EncounterExecution
	9,  // 9: GetExecutionByUserIdResponse.execution:type_name -> EncounterExecution
	3,  // 10: EncounterService.CreateEncounterRpc:input_type -> CreateEncounterRequest
	5,  // 11: EncounterService.GetAllEncountersRpc:input_type -> GetAllEncountersRequest
	7,  // 12: EncounterService.GetEncounterByIDRpc:input_type -> GetEncounterByIDRequest
	10, // 13: EncounterExecutionService.CreateExecutionRpc:input_type -> CreateExecutionRequest
	12, // 14: EncounterExecutionService.GetAllExecutionsRpc:input_type -> GetAllExecutionsRequest
	14, // 15: EncounterExecutionService.GetExecutionByUserIDRpc:input_type -> GetExecutionByUserIdRequest
	16, // 16: EncounterExecutionService.UpdateExecutionRpc:input_type -> UpdateExecutionRequest
	4,  // 17: EncounterService.CreateEncounterRpc:output_type -> CreateEncounterResponse
	6,  // 18: EncounterService.GetAllEncountersRpc:output_type -> GetAllEncountersResponse
	8,  // 19: EncounterService.GetEncounterByIDRpc:output_type -> GetEncounterByIDResponse
	11, // 20: EncounterExecutionService.CreateExecutionRpc:output_type -> CreateExecutionResponse
	13, // 21: EncounterExecutionService.GetAllExecutionsRpc:output_type -> GetAllExecutionsResponse
	15, // 22: EncounterExecutionService.GetExecutionByUserIDRpc:output_type -> GetExecutionByUserIdResponse
	17, // 23: EncounterExecutionService.UpdateExecutionRpc:output_type -> UpdateExecutionResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_encounters_service_proto_init() }
func file_encounters_service_proto_init() {
	if File_encounters_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encounters_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Encounter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEncounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllEncountersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllEncountersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEncounterByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEncounterByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncounterExecution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExecutionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllExecutionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllExecutionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExecutionByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExecutionByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExecutionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encounters_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_encounters_service_proto_goTypes,
		DependencyIndexes: file_encounters_service_proto_depIdxs,
		EnumInfos:         file_encounters_service_proto_enumTypes,
		MessageInfos:      file_encounters_service_proto_msgTypes,
	}.Build()
	File_encounters_service_proto = out.File
	file_encounters_service_proto_rawDesc = nil
	file_encounters_service_proto_goTypes = nil
	file_encounters_service_proto_depIdxs = nil
}
