version: '3.9'

services:
  encounters-server:
    container_name: encounters-server
    image: encounters/go-server:1.0
    build: .
    environment:
      DATABASE_URL: "host=go_db_encounters user=postgres password=postgres dbname=SOA-encounters sslmode=disable"
    ports:
      - 8083:8083
    depends_on:
      - go_db_encounters
  go_db_encounters:
    container_name: go_db_encounters
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SOA-encounters
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}