version: '3.9'

services:
  tours-server:
    container_name: tours-server
    image: tours/go-server:1.0
    build: .
    environment:
      DATABASE_URL: "host=go_db_tours user=postgres password=postgres dbname=SOA-tours sslmode=disable"
    ports:
      - 8081:8081
    depends_on:
      - go_db_tours
  go_db_tours:
    container_name: go_db_tours
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SOA-tours
    ports:
      - 5431:5431
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}