// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0--rc3
// source: tours_service.proto

package TOURS

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ToursService_TourCreationRpc_FullMethodName      = "/ToursService/TourCreationRpc"
	ToursService_GetPublishedToursRpc_FullMethodName = "/ToursService/GetPublishedToursRpc"
	ToursService_PurchaseToursRpc_FullMethodName     = "/ToursService/PurchaseToursRpc"
	ToursService_GetPurchasedToursRpc_FullMethodName = "/ToursService/GetPurchasedToursRpc"
	ToursService_GetAuthorToursRpc_FullMethodName    = "/ToursService/GetAuthorToursRpc"
	ToursService_UpdateTourRpc_FullMethodName        = "/ToursService/UpdateTourRpc"
)

// ToursServiceClient is the client API for ToursService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToursServiceClient interface {
	TourCreationRpc(ctx context.Context, in *TourCreationRequest, opts ...grpc.CallOption) (*TourCreationResponse, error)
	GetPublishedToursRpc(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllToursResponse, error)
	PurchaseToursRpc(ctx context.Context, in *PurchaseToursRequest, opts ...grpc.CallOption) (*PurchaseToursResponse, error)
	GetPurchasedToursRpc(ctx context.Context, in *UserPurchaseTourRequest, opts ...grpc.CallOption) (*UserPurchaseTourResponse, error)
	GetAuthorToursRpc(ctx context.Context, in *AuthorToursRequest, opts ...grpc.CallOption) (*AuthorToursResponse, error)
	UpdateTourRpc(ctx context.Context, in *UpdateTourRequest, opts ...grpc.CallOption) (*TourCreationResponse, error)
}

type toursServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToursServiceClient(cc grpc.ClientConnInterface) ToursServiceClient {
	return &toursServiceClient{cc}
}

func (c *toursServiceClient) TourCreationRpc(ctx context.Context, in *TourCreationRequest, opts ...grpc.CallOption) (*TourCreationResponse, error) {
	out := new(TourCreationResponse)
	err := c.cc.Invoke(ctx, ToursService_TourCreationRpc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetPublishedToursRpc(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllToursResponse, error) {
	out := new(GetAllToursResponse)
	err := c.cc.Invoke(ctx, ToursService_GetPublishedToursRpc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) PurchaseToursRpc(ctx context.Context, in *PurchaseToursRequest, opts ...grpc.CallOption) (*PurchaseToursResponse, error) {
	out := new(PurchaseToursResponse)
	err := c.cc.Invoke(ctx, ToursService_PurchaseToursRpc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetPurchasedToursRpc(ctx context.Context, in *UserPurchaseTourRequest, opts ...grpc.CallOption) (*UserPurchaseTourResponse, error) {
	out := new(UserPurchaseTourResponse)
	err := c.cc.Invoke(ctx, ToursService_GetPurchasedToursRpc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetAuthorToursRpc(ctx context.Context, in *AuthorToursRequest, opts ...grpc.CallOption) (*AuthorToursResponse, error) {
	out := new(AuthorToursResponse)
	err := c.cc.Invoke(ctx, ToursService_GetAuthorToursRpc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) UpdateTourRpc(ctx context.Context, in *UpdateTourRequest, opts ...grpc.CallOption) (*TourCreationResponse, error) {
	out := new(TourCreationResponse)
	err := c.cc.Invoke(ctx, ToursService_UpdateTourRpc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToursServiceServer is the server API for ToursService service.
// All implementations must embed UnimplementedToursServiceServer
// for forward compatibility
type ToursServiceServer interface {
	TourCreationRpc(context.Context, *TourCreationRequest) (*TourCreationResponse, error)
	GetPublishedToursRpc(context.Context, *emptypb.Empty) (*GetAllToursResponse, error)
	PurchaseToursRpc(context.Context, *PurchaseToursRequest) (*PurchaseToursResponse, error)
	GetPurchasedToursRpc(context.Context, *UserPurchaseTourRequest) (*UserPurchaseTourResponse, error)
	GetAuthorToursRpc(context.Context, *AuthorToursRequest) (*AuthorToursResponse, error)
	UpdateTourRpc(context.Context, *UpdateTourRequest) (*TourCreationResponse, error)
	mustEmbedUnimplementedToursServiceServer()
}

// UnimplementedToursServiceServer must be embedded to have forward compatible implementations.
type UnimplementedToursServiceServer struct {
}

func (UnimplementedToursServiceServer) TourCreationRpc(context.Context, *TourCreationRequest) (*TourCreationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TourCreationRpc not implemented")
}
func (UnimplementedToursServiceServer) GetPublishedToursRpc(context.Context, *emptypb.Empty) (*GetAllToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublishedToursRpc not implemented")
}
func (UnimplementedToursServiceServer) PurchaseToursRpc(context.Context, *PurchaseToursRequest) (*PurchaseToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseToursRpc not implemented")
}
func (UnimplementedToursServiceServer) GetPurchasedToursRpc(context.Context, *UserPurchaseTourRequest) (*UserPurchaseTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPurchasedToursRpc not implemented")
}
func (UnimplementedToursServiceServer) GetAuthorToursRpc(context.Context, *AuthorToursRequest) (*AuthorToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorToursRpc not implemented")
}
func (UnimplementedToursServiceServer) UpdateTourRpc(context.Context, *UpdateTourRequest) (*TourCreationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTourRpc not implemented")
}
func (UnimplementedToursServiceServer) mustEmbedUnimplementedToursServiceServer() {}

// UnsafeToursServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToursServiceServer will
// result in compilation errors.
type UnsafeToursServiceServer interface {
	mustEmbedUnimplementedToursServiceServer()
}

func RegisterToursServiceServer(s grpc.ServiceRegistrar, srv ToursServiceServer) {
	s.RegisterService(&ToursService_ServiceDesc, srv)
}

func _ToursService_TourCreationRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).TourCreationRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_TourCreationRpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).TourCreationRpc(ctx, req.(*TourCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetPublishedToursRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetPublishedToursRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetPublishedToursRpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetPublishedToursRpc(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_PurchaseToursRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).PurchaseToursRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_PurchaseToursRpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).PurchaseToursRpc(ctx, req.(*PurchaseToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetPurchasedToursRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPurchaseTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetPurchasedToursRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetPurchasedToursRpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetPurchasedToursRpc(ctx, req.(*UserPurchaseTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetAuthorToursRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetAuthorToursRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetAuthorToursRpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetAuthorToursRpc(ctx, req.(*AuthorToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_UpdateTourRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).UpdateTourRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_UpdateTourRpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).UpdateTourRpc(ctx, req.(*UpdateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToursService_ServiceDesc is the grpc.ServiceDesc for ToursService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToursService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ToursService",
	HandlerType: (*ToursServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TourCreationRpc",
			Handler:    _ToursService_TourCreationRpc_Handler,
		},
		{
			MethodName: "GetPublishedToursRpc",
			Handler:    _ToursService_GetPublishedToursRpc_Handler,
		},
		{
			MethodName: "PurchaseToursRpc",
			Handler:    _ToursService_PurchaseToursRpc_Handler,
		},
		{
			MethodName: "GetPurchasedToursRpc",
			Handler:    _ToursService_GetPurchasedToursRpc_Handler,
		},
		{
			MethodName: "GetAuthorToursRpc",
			Handler:    _ToursService_GetAuthorToursRpc_Handler,
		},
		{
			MethodName: "UpdateTourRpc",
			Handler:    _ToursService_UpdateTourRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours_service.proto",
}
